# Generated by Django 2.2.6 on 2022-11-29 08:22

from django.db import migrations, models
import django.utils.timezone
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=150)),
                ('message_email', models.CharField(max_length=150)),
                ('message_subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionCreateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatorReferral', models.CharField(max_length=7)),
                ('FriendReferral', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=150)),
                ('message_email', models.CharField(max_length=150)),
                ('message_subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=2000)),
                ('SaturnTileRef', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tileusername', models.CharField(default='Username', max_length=50)),
                ('tilepassword', models.CharField(default='Password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OldMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=2000)),
                ('SaturnTileRef', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tileusername', models.CharField(default='Username', max_length=50)),
                ('tilepassword', models.CharField(default='Password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SaturnConnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=15)),
                ('friend', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SaturnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaturnUser', models.CharField(max_length=150)),
                ('SaturnAction', models.CharField(max_length=150)),
                ('SaturnTileRef', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SaturnReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaturnUser', models.CharField(max_length=50)),
                ('SaturnEmail', models.CharField(default='null', max_length=50)),
                ('ReferralCode', models.CharField(max_length=7)),
                ('Upvote', models.PositiveIntegerField(default=0)),
                ('Downvote', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SavedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=2000)),
                ('SaturnTileRef', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('tileusername', models.CharField(default='Username', max_length=50)),
                ('tilepassword', models.CharField(default='Password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('currency', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=2000)),
                ('SaturnTileRef', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('tileusername', encrypted_model_fields.fields.EncryptedCharField(default='Username')),
                ('tilepassword', encrypted_model_fields.fields.EncryptedCharField(default='Username')),
            ],
        ),
        migrations.CreateModel(
            name='UserReferral2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('main_user', models.CharField(max_length=50)),
                ('third_degree_users', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
            options={
                'unique_together': {('main_user', 'third_degree_users')},
            },
        ),
        migrations.CreateModel(
            name='UserReferral1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('main_user', models.CharField(max_length=50)),
                ('second_degree_users', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
            options={
                'unique_together': {('main_user', 'second_degree_users')},
            },
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('main_user', models.CharField(blank=True, max_length=50)),
                ('first_degree_users', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
            options={
                'unique_together': {('main_user', 'first_degree_users')},
            },
        ),
    ]
